[stream_to_query]
stream = "decoder_output"
buffer_size_s = 2.0
[lsl_outlet]
name="control_signal"
nominal_freq_hz = "derive"       # either a float or "derive" -> take same as input
format = "float32"
type="control_signal"

[controller]
threshold=15_000
